version: '3.8'

services:
  frontend:
    build: 
      context: ./frontend
      # dockerfile: Dockerfile #prod
      dockerfile: Dockerfile.dev
    ports:
      # - "${FRONTEND_PORT:-3000}:80"
      - "${FRONTEND_PORT:-3000}:3000" # for hot reload
    environment:
      - REACT_APP_API_URL=${API_URL:-http://localhost:8000}
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
      - CHOKIDAR_INTERVAL=10
      - HOST=0.0.0.0
    volumes:
      - ./frontend:/app
      - /app/node_modules
      # - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "${BACKEND_PORT:-8000}:8000"
    depends_on:
      - postgres
      - pipeline  # Add explicit dependency on pipeline
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:${POSTGRES_PORT}/${POSTGRES_DB}
      - GOOGLE_DRIVE_CREDENTIALS_PATH=/app/credentials/google_drive_credentials.json
      - GOOGLE_DRIVE_BASE_FOLDER_ID=${GOOGLE_DRIVE_BASE_FOLDER_ID}
    volumes:
      - ./backend:/app
      - ./queries:/queries:ro
      - ./queries:/app/queries
    networks:
      - app-network
    restart: unless-stopped

  postgres:
    image: postgres:17
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network
    restart: unless-stopped

  pipeline:
    build: 
      context: ./pipeline
      dockerfile: Dockerfile
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:${POSTGRES_PORT}/${POSTGRES_DB}
    depends_on:
      - postgres
    networks:
      - app-network
    shm_size: 2gb  # Increase shared memory for browser
    deploy:
      resources:
        limits:
          memory: 4G  # Limit memory to 4GB
        reservations:
          memory: 1G  # Reserve at least 1GB

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
    driver: local