SELECT
	-- region,
	-- country,
	-- country_code,
	project_id,
	TO_CHAR(agreement_signing_date, 'YYYY-MM-DD') AS agreement_signing_date,
	TO_CHAR(board_approval_date, 'YYYY-MM-DD') AS board_approval_date,
	borrower,
	NULLIF(TO_CHAR(borrowers_obligation_us_, '999,999,999,999.99'), '') AS borrowers_obligation_usd,
	NULLIF(TO_CHAR(cancelled_amount_us_, '999,999,999,999.99'), '') AS cancelled_amount_usd,
	TO_CHAR(closed_date_most_recent, 'YYYY-MM-DD') AS closed_date_most_recent,
	credit_number,
	credit_status,
	NULLIF(TO_CHAR(credits_held_us_, '999,999,999,999.99'), '') AS credits_held_us_,
	currency_of_commitment,
	NULLIF(TO_CHAR(disbursed_amount_us_, '999,999,999,999.99'), '') AS disbursed_amount_usd,
	NULLIF(TO_CHAR(due_3rd_party_us_, '999,999,999,999.99'), '') AS due_3rd_party_usd,
	NULLIF(TO_CHAR(due_to_ida_us_, '999,999,999,999.99'), '') AS due_to_ida_usd,
	TO_CHAR(effective_date_most_recent, 'YYYY-MM-DD') AS effective_date_most_recent,
	TO_CHAR(end_of_period, 'YYYY-MM-DD') AS end_of_period,
	NULLIF(TO_CHAR(exchange_adjustment_us_, '999,999,999,999.99'), '') AS exchange_adjustment_usd,
	TO_CHAR(first_repayment_date, 'YYYY-MM-DD') AS first_repayment_date,
	TO_CHAR(last_disbursement_date, 'YYYY-MM-DD') AS last_disbursement_date,
	TO_CHAR(last_repayment_date, 'YYYY-MM-DD') AS last_repayment_date,
	NULLIF(TO_CHAR(original_principal_amount_us_, '999,999,999,999.99'), '') AS original_principal_amount_usd,
	project_name,
	NULLIF(TO_CHAR(repaid_3rd_party_us_, '999,999,999,999.99'), '') AS repaid_3rd_party_usd,
	NULLIF(TO_CHAR(repaid_to_ida_us_, '999,999,999,999.99'), '') AS repaid_to_ida_usd,
	service_charge_rate,
	NULLIF(TO_CHAR(sold_3rd_party_us_, '999,999,999,999.99'), '') AS sold_3rd_party_usd,
	NULLIF(TO_CHAR(undisbursed_amount_us_, '999,999,999,999.99'), '') AS undisbursed_amount_usd,
	NULLIF(TO_CHAR(total_repayment, '999,999,999,999.99'), '') AS total_repayment,
	repayment_rate,
	TO_CHAR(processed_at, 'YYYY-MM-DD') AS processed_at
FROM wb_credit_statements
WHERE
	country = 'Madagascar'
ORDER BY
	project_id,
	agreement_signing_date