# Format:
# query_path:           # Relative path to the query file from queries directory
#   folder_id: string   # Google Drive folder ID where the file should be uploaded
#   filename: string    # Name of the file in Google Drive

"Madagascar/contract_awards_country_distribution.sql":
  drive_path: "MADAGASCAR"
  filename: "Contract Awards Country Distribution.xlsx"

"Madagascar/contract_awards_supplier_distribution.sql":
  drive_path: "MADAGASCAR"
  filename: "Contract Awards Supplier Distribution.xlsx"

"Madagascar/credit_statements.sql":
  drive_path: "MADAGASCAR"
  filename: "Credit Statements.xlsx"

"Madagascar/projects_list.sql":
  drive_path: "MADAGASCAR"
  filename: "Project List.xlsx"

"Madagascar/UN_organizations.sql":
  drive_path: "MADAGASCAR"
  filename: "UN Orgs Contracts.xlsx"

"Madagascar/contract_percentage_by_country.sql":
  drive_path: "MADAGASCAR"
  filename: "Contract Percentage By Country.xlsx"

"Madagascar/pivoted_percentage.sql":
  drive_path: "MADAGASCAR"
  filename: "Country Contract Percentage per Project.xlsx"

"Madagascar/project_associated_cost_comparison.sql":
  drive_path: "MADAGASCAR"
  filename: "Project Associated Cost Comparison.xlsx"

"Madagascar/trust_fund_commitments.sql":
  drive_path: "MADAGASCAR"
  filename: "Trust Fund Commitments.xlsx"

"Madagascar/FIF_contributions.sql":
  drive_path: "MADAGASCAR"
  filename: "FIF Contributions.xlsx"

"Madagascar/world_bank_GEF_project.sql":
  drive_path: "MADAGASCAR"
  filename: "GEF Projects involving Madagascar.xlsx"